"""add phone to drivers table

Revision ID: 0a4796c76842
Revises: a7ea5d8463b9
Create Date: 2026-10-04 02:07:48.032419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4796c76842'
down_revision: Union[str, Sequence[str], None] = 'a7ea5d8463b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'phone')
    # ### end Alembic commands ###
