"""add index to driver phone

Revision ID: 9e7467cf1b5e
Revises: 3e0c15834499
Create Date: 2026-10-05 16:05:40.089603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7467cf1b5e'
down_revision: Union[str, Sequence[str], None] = '3e0c15834499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drivers_phone'), 'drivers', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_phone'), table_name='drivers')
    # ### end Alembic commands ###
